<a href="https://colab.research.google.com/github/debha-dev/nithub-ml-track/blob/week2-pandas/Data_science_salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project: Data Science salary
## Name: Itulua Cheluh
## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

<a id='intro'></a>
## Section I: Introduction

**Dataset**: [Data Science Salary](https://d17h27t6h515a5.cloudfront.net/topher/2017/October/59dd2e9a_noshowappointments-kagglev2-may-2016/noshowappointments-kagglev2-may-2016.csv)

**Description**: This dataset provides information on salaries of data science professionals across the world. Each row represents a specific job role in the data industry, along with key details like experience level, job title, company location, and salary in both local currency and USD. The dataset is useful for exploring salary trends based on region, job type, experience, and company size.

**Columns Description**
- **`work_year`**:  The year in which the salary was paid (e.g., 2020, 2021, 2022).
- **`experience_level`**: The level of experience of the employee (e.g., Entry-level, Mid-level, Senior, Executive)
- **`employment_type`**:The nature of the employment (e.g., Full-time, Part-time, Contract, Freelance).
- **`job_title`**: The specific role or title of the employee (e.g., Data Scientist, Machine Learning Engineer, Data Analyst).
- **`salary`**:  The salary paid in the employee’s local currency.
- **`salary_currency`**: The currency in which the salary was paid (e.g., USD, EUR, INR).
- **`salary_in_usd`**:  The salary converted to US Dollars for easy comparison across countries.
- **`company_location`**:  The country where the company is located.
- **`company_size`**:The size of the company based on the number of employees (e.g., Small, Medium, Large)

***We will be investigating the dataset to uncover the following:***
1. What factors influence a data science professional's salary globally?

2. How do salary trends vary across experience levels, job titles, company sizes, and locations?

**Research Areas**
1. `Target Variable (salary_in_usd)`: We'll be analyzing the salary in USD as the main variable of interest to allow uniform comparison across all regions, regardless of local currency.
2. `Univariate Analysis`: We'll explore each feature individually to observe its distribution and potential impact on salary.
For example:

How does `experience_level` affect salary?

What are the most common `job_titles` and their corresponding average salaries?

Does `company_size` influence how much professionals earn?
3. `Multivariate Analysis`: We'll analyze the interaction between two or more variables and their collective impact on salary.
Questions include:

How does `experience_level` interact with `company_size` or `employment_type` in predicting salary?

Are there countries or regions where salaries are consistently higher for the same job title?

What combinations of job title and employment type yield the highest pay?

**LIMITATIONS**

1. The dataset may not reflect salaries in real-time or in local market context, especially due to conversion into USD. Currency exchange rate fluctuations could introduce inaccuracies.
2. Some columns contain categorical data that may need encoding or simplification for certain types of analysis. Also, abbreviations like `EN`, `MI`, `SE`, `EX` in `experience_level` require decoding.
3. The `company_location` field does not include geographical coordinates or continent-level grouping, limiting location-based heatmaps or geospatial salary analysis.
4. The Neighbourhood Data should have included the gographical coordinates for better analysis as to how a location can affect the choice of the patient

In [ ]:
# importing Required library

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
!gdown --id 1rGOdAjrXznDMt9gOyorxyS5uoZ_ZBGD5

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1rGOdAjrXznDMt9gOyorxyS5uoZ_ZBGD5
To: /content/Data Science Salary 2021 to 2023.csv
100% 192k/192k [00:00<00:00, 113MB/s]

In [ ]:
df = pd.read_csv("/content/Data Science Salary 2021 to 2023.csv") #TO read a dataset

df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L

In [ ]:
df.dtypes # to check the data_type of each column

work_year            int64
experience_level    object
employment_type     object
job_title           object
salary               int64
salary_currency     object
salary_in_usd        int64
company_location    object
company_size        object
dtype: object

In [ ]:
df.describe()

         work_year        salary  salary_in_usd
count  3761.000000  3.761000e+03    3761.000000
mean   2022.374103  1.905999e+05  137555.178942
std       0.691252  6.711457e+05   63022.267974
min    2020.000000  6.000000e+03    5132.000000
25%    2022.000000  1.000000e+05   95000.000000
50%    2022.000000  1.375000e+05  135000.000000
75%    2023.000000  1.800000e+05  175000.000000
max    2023.000000  3.040000e+07  450000.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         3761 non-null   int64
 1   experience_level  3761 non-null   object
 2   employment_type   3761 non-null   object
 3   job_title         3761 non-null   object
 4   salary            3761 non-null   int64
 5   salary_currency   3761 non-null   object
 6   salary_in_usd     3761 non-null   int64
 7   company_location  3761 non-null   object
 8   company_size      3761 non-null   object
dtypes: int64(3), object(6)
memory usage: 264.6+ KB

In [ ]:
df.tail() # get the values in the last five column

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
3756,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,M
3757,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,S
3758,2020,SE,FT,Data Science Manager,190200,USD,190200,US,M
3759,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,S
3760,2020,SE,FT,Data Scientist,412000,USD,412000,US,L

In [ ]:
df.head() #get the values in the first five column

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L

In [ ]:
df.experience_level.value_counts() # to get the value_count of very value in each row

experience_level
SE    2518
MI     809
EN     320
EX     114
Name: count, dtype: int64

In [ ]:
df # get the whole dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,EN,FT,Applied Scientist,213660,USD,213660,US,L
1,2023,EN,FT,Applied Scientist,130760,USD,130760,US,L
2,2023,EN,FT,Data Quality Analyst,100000,USD,100000,NG,L
3,2023,EN,FT,Compliance Data Analyst,30000,USD,30000,NG,L
4,2023,EN,FT,Applied Scientist,204620,USD,204620,US,L
...,...,...,...,...,...,...,...,...,...
3756,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,M
3757,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,S
3758,2020,SE,FT,Data Science Manager,190200,USD,190200,US,M
3759,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,S
3760,2020,SE,FT,Data Scientist,412000,USD,412000,US,L

In [ ]:
#create a dictionary with the key and values you waht to use
experience_dict = { 'EN': 'Entry-level', 'MI': 'Mid-level', 'SE': 'Senior', 'EX': 'Executive'}

#map the dictionary to the column on the dataset
df.experience_level = df.experience_level.map(experience_dict)
df.head() # To view the first five row

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,Entry-level,FT,Applied Scientist,213660,USD,213660,US,L
1,2023,Entry-level,FT,Applied Scientist,130760,USD,130760,US,L
2,2023,Entry-level,FT,Data Quality Analyst,100000,USD,100000,NG,L
3,2023,Entry-level,FT,Compliance Data Analyst,30000,USD,30000,NG,L
4,2023,Entry-level,FT,Applied Scientist,204620,USD,204620,US,L

In [ ]:
df.experience_level.value_counts()

experience_level
Senior         2518
Mid-level       809
Entry-level     320
Executive       114
Name: count, dtype: int64

In [ ]:
company_dict = {'S': 'Small', 'M': 'Medium', 'L': 'Large'}
df.company_size = df.company_size.map(company_dict)
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,Entry-level,FT,Applied Scientist,213660,USD,213660,US,Large
1,2023,Entry-level,FT,Applied Scientist,130760,USD,130760,US,Large
2,2023,Entry-level,FT,Data Quality Analyst,100000,USD,100000,NG,Large
3,2023,Entry-level,FT,Compliance Data Analyst,30000,USD,30000,NG,Large
4,2023,Entry-level,FT,Applied Scientist,204620,USD,204620,US,Large

In [ ]:
employment_dict = {'FT': 'Full-time', 'PT': 'Part-time', 'CT': 'Contract', 'FL': 'Freelance'}
df.employment_type = df.employment_type.map(employment_dict)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large
3,2023,Entry-level,Full-time,Compliance Data Analyst,30000,USD,30000,NG,Large
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large
...,...,...,...,...,...,...,...,...,...
3756,2020,Senior,Full-time,Principal Data Scientist,130000,EUR,148261,DE,Medium
3757,2020,Senior,Full-time,Data Scientist,80000,EUR,91237,AT,Small
3758,2020,Senior,Full-time,Data Science Manager,190200,USD,190200,US,Medium
3759,2020,Senior,Full-time,Machine Learning Engineer,40000,EUR,45618,HR,Small
3760,2020,Senior,Full-time,Data Scientist,412000,USD,412000,US,Large

In [ ]:
!pip install country_converter # install country converter

Requirement already satisfied: country_converter in /usr/local/lib/python3.11/dist-packages (1.3.1)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.11/dist-packages (from country_converter) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->country_converter) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->country_converter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->country_converter) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->country_converter) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0->country_converter) (1.17.0)

In [ ]:
import country_converter as coco

In [ ]:
cc = coco.CountryConverter()

df['country'] = cc.convert(names=df['company_location'], to='name_short')
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria
3,2023,Entry-level,Full-time,Compliance Data Analyst,30000,USD,30000,NG,Large,Nigeria
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States

In [ ]:
df.job_title.unique()

array(['Applied Scientist', 'Data Quality Analyst',
       'Compliance Data Analyst', 'Machine Learning Engineer',
       'Research Scientist', 'Data Engineer', 'Data Analyst',
       'Data Scientist', 'BI Data Engineer', 'Research Engineer',
       'Business Data Analyst', 'Autonomous Vehicle Technician',
       'Applied Machine Learning Scientist', 'AI Programmer',
       'AI Developer', 'Computer Vision Engineer', 'BI Developer',
       'Big Data Engineer', 'Deep Learning Engineer', 'Head of Data',
       'Analytics Engineer', 'Data Architect', 'Director of Data Science',
       'Head of Data Science', 'Data Analytics Manager', 'ML Engineer',
       'Applied Machine Learning Engineer', 'Applied Data Scientist',
       'ETL Engineer', 'Data Specialist', 'Lead Data Analyst',
       'Data Manager', 'Machine Learning Scientist', 'MLOps Engineer',
       'Financial Data Analyst', 'Software Data Engineer',
       'Data Science Manager', 'Data Science Consultant',
       'Machine Learning Infrastructure Engineer', 'Insight Analyst',
       'AI Scientist', 'Data Infrastructure Engineer',
       'Data Science Lead', 'Product Data Analyst', 'Data Analytics Lead',
       'Machine Learning Research Engineer', 'Principal Data Scientist',
       'Data Modeler', 'Business Intelligence Engineer',
       'Data Strategist', 'Data DevOps Engineer',
       'Machine Learning Researcher', 'Cloud Database Engineer',
       'Data Operations Engineer', 'Deep Learning Researcher',
       'BI Analyst', 'Data Analytics Specialist', 'BI Data Analyst',
       'Machine Learning Software Engineer', 'Big Data Architect',
       'Computer Vision Software Engineer', 'Azure Data Engineer',
       'Data Lead', 'Data Science Engineer', 'NLP Engineer',
       'Machine Learning Developer', 'Data Analytics Engineer',
       'Data Analytics Consultant', '3D Computer Vision Researcher',
       'Lead Data Engineer', 'Head of Machine Learning',
       'Data Scientist Lead', 'Lead Data Scientist', 'ETL Developer',
       'Principal Data Analyst', 'Manager Data Management',
       'Principal Machine Learning Engineer',
       'Data Management Specialist', 'Data Science Tech Lead',
       'Cloud Data Engineer', 'Data Operations Analyst',
       'Marketing Data Analyst', 'Product Data Scientist',
       'Principal Data Architect', 'Machine Learning Manager',
       'Lead Machine Learning Engineer', 'Marketing Data Engineer',
       'Power BI Developer', 'Cloud Data Architect',
       'Principal Data Engineer', 'Staff Data Scientist',
       'Finance Data Analyst', 'Staff Data Analyst'], dtype=object)

In [ ]:
df.job_title.value_counts()

job_title
Data Engineer                1040
Data Scientist                840
Data Analyst                  614
Machine Learning Engineer     291
Analytics Engineer            103
                             ...
Marketing Data Engineer         1
Cloud Data Architect            1
Staff Data Scientist            1
Finance Data Analyst            1
Staff Data Analyst              1
Name: count, Length: 93, dtype: int64

In [ ]:
df['job_title'] = df['job_title'].apply(lambda x: "Data Analyst" if "data analyst" in x.lower() else x)
df['job_title'] = df['job_title'].apply(lambda x: "Data Scientist" if "data scientist" in x.lower() else x)
df['job_title'] = df['job_title'].apply(lambda x: "Data Engineer" if "data engineer" in x.lower() else x)

In [ ]:
df.job_title.value_counts()

job_title
Data Engineer                 1067
Data Scientist                 871
Data Analyst                   664
Machine Learning Engineer      291
Analytics Engineer             103
                              ...
Data Management Specialist       1
Principal Data Architect         1
Data Science Tech Lead           1
Power BI Developer               1
Cloud Data Architect             1
Name: count, Length: 69, dtype: int64

In [ ]:
df.salary_currency.value_counts()

salary_currency
USD    3229
EUR     236
GBP     162
INR      60
CAD      25
AUD       9
SGD       6
BRL       6
PLN       5
CHF       4
DKK       3
HUF       3
TRY       3
JPY       3
THB       2
HKD       1
CZK       1
ILS       1
CLP       1
MXN       1
Name: count, dtype: int64

In [ ]:
# get salary_range
def get_salary_range(salary):
    if salary < 30000:
        return 'Low'
    elif salary < 80000:
        return 'Medium'
    elif salary < 150000:
        return 'High'
    else:
        return 'Very High'

df['salary_range'] = df['salary_in_usd'].apply(get_salary_range)

In [ ]:
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country,salary_range
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States,Very High
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States,High
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria,High
3,2023,Entry-level,Full-time,Data Analyst,30000,USD,30000,NG,Large,Nigeria,Medium
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States,Very High
...,...,...,...,...,...,...,...,...,...,...,...
3756,2020,Senior,Full-time,Data Scientist,130000,EUR,148261,DE,Medium,Germany,High
3757,2020,Senior,Full-time,Data Scientist,80000,EUR,91237,AT,Small,Austria,High
3758,2020,Senior,Full-time,Data Science Manager,190200,USD,190200,US,Medium,United States,Very High
3759,2020,Senior,Full-time,Machine Learning Engineer,40000,EUR,45618,HR,Small,Croatia,Medium
3760,2020,Senior,Full-time,Data Scientist,412000,USD,412000,US,Large,United States,Very High

In [ ]:
df['years_since_2010'] = df['work_year'] - 2010 # how many years working in the company since 2010
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country,salary_range,years_since_2010
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States,Very High,13
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States,High,13
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria,High,13
3,2023,Entry-level,Full-time,Data Analyst,30000,USD,30000,NG,Large,Nigeria,Medium,13
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States,Very High,13

In [ ]:
df['salary_in_ngn'] = df['salary_in_usd'].apply(lambda x: x * 1500)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country,salary_range,years_since_2010,salary_in_ngn
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States,Very High,13,320490000
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States,High,13,196140000
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria,High,13,150000000
3,2023,Entry-level,Full-time,Data Analyst,30000,USD,30000,NG,Large,Nigeria,Medium,13,45000000
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States,Very High,13,306930000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3756,2020,Senior,Full-time,Data Scientist,130000,EUR,148261,DE,Medium,Germany,High,10,222391500
3757,2020,Senior,Full-time,Data Scientist,80000,EUR,91237,AT,Small,Austria,High,10,136855500
3758,2020,Senior,Full-time,Data Science Manager,190200,USD,190200,US,Medium,United States,Very High,10,285300000
3759,2020,Senior,Full-time,Machine Learning Engineer,40000,EUR,45618,HR,Small,Croatia,Medium,10,68427000
3760,2020,Senior,Full-time,Data Scientist,412000,USD,412000,US,Large,United States,Very High,10,618000000

In [ ]:
df['monthly_salary'] = df['salary_in_ngn'] / 12
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country,salary_range,years_since_2010,salary_in_ngn,monthly_salary
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States,Very High,13,320490000,26707500.0
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States,High,13,196140000,16345000.0
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria,High,13,150000000,12500000.0
3,2023,Entry-level,Full-time,Data Analyst,30000,USD,30000,NG,Large,Nigeria,Medium,13,45000000,3750000.0
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States,Very High,13,306930000,25577500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3756,2020,Senior,Full-time,Data Scientist,130000,EUR,148261,DE,Medium,Germany,High,10,222391500,18532625.0
3757,2020,Senior,Full-time,Data Scientist,80000,EUR,91237,AT,Small,Austria,High,10,136855500,11404625.0
3758,2020,Senior,Full-time,Data Science Manager,190200,USD,190200,US,Medium,United States,Very High,10,285300000,23775000.0
3759,2020,Senior,Full-time,Machine Learning Engineer,40000,EUR,45618,HR,Small,Croatia,Medium,10,68427000,5702250.0
3760,2020,Senior,Full-time,Data Scientist,412000,USD,412000,US,Large,United States,Very High,10,618000000,51500000.0

In [ ]:
size_to_employee_count = {
    'Small': 100,
    'Medium': 500,
    'Large': 1000
}

df['average_salary_per_employee'] = df.apply(
    lambda row: row['salary_in_ngn'] / size_to_employee_count.get(row['company_size'], 1),
    axis=1
)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size,country,salary_range,years_since_2010,salary_in_ngn,monthly_salary,average_salary_per_employee
0,2023,Entry-level,Full-time,Applied Scientist,213660,USD,213660,US,Large,United States,Very High,13,320490000,26707500.0,320490.0
1,2023,Entry-level,Full-time,Applied Scientist,130760,USD,130760,US,Large,United States,High,13,196140000,16345000.0,196140.0
2,2023,Entry-level,Full-time,Data Quality Analyst,100000,USD,100000,NG,Large,Nigeria,High,13,150000000,12500000.0,150000.0
3,2023,Entry-level,Full-time,Data Analyst,30000,USD,30000,NG,Large,Nigeria,Medium,13,45000000,3750000.0,45000.0
4,2023,Entry-level,Full-time,Applied Scientist,204620,USD,204620,US,Large,United States,Very High,13,306930000,25577500.0,306930.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3756,2020,Senior,Full-time,Data Scientist,130000,EUR,148261,DE,Medium,Germany,High,10,222391500,18532625.0,444783.0
3757,2020,Senior,Full-time,Data Scientist,80000,EUR,91237,AT,Small,Austria,High,10,136855500,11404625.0,1368555.0
3758,2020,Senior,Full-time,Data Science Manager,190200,USD,190200,US,Medium,United States,Very High,10,285300000,23775000.0,570600.0
3759,2020,Senior,Full-time,Machine Learning Engineer,40000,EUR,45618,HR,Small,Croatia,Medium,10,68427000,5702250.0,684270.0
3760,2020,Senior,Full-time,Data Scientist,412000,USD,412000,US,Large,United States,Very High,10,618000000,51500000.0,618000.0